---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfy-ui
  template:
    metadata:
      labels:
        app: comfy-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-da-gpu-2
      runtimeClassName: nvidia
      containers:
        - name: comfy-ui
          image: yanwk/comfyui-boot:cu128-slim
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          ports:
            - containerPort: 8188
          volumeMounts:
            - mountPath: /root
              name: comfy-ui-data
      volumes:
        - name: comfy-ui-data
          hostPath:
            path: /data/comfy-ui
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: comfy-ui
spec:
  selector:
    app: comfy-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8188
  type: ClusterIP