apiVersion: apps/v1
kind: Deployment
metadata:
  name: mni-pusher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mni-pusher
  template:
    metadata:
      labels:
        app: mni-pusher
    spec:
      containers:
        - name: mni-pusher
          image: zot.ingtra.net/library/mni-tools:latest
          imagePullPolicy: Always
          args: ["--config", "/config/config.yaml"]
          env:
            - name: FIREFLY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: FIREFLY_TOKEN
