apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: airflow
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`airflow.ig.ingtra.net`)
      services:
        - kind: Service
          name: airflow-api-server
          namespace: airflow
          port: 8080
  tls:
    secretName: ig-ingtra-net-tls
